/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ApiOutlined: typeof import('@ant-design/icons-vue')['ApiOutlined']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATypographyLink: typeof import('ant-design-vue/es')['TypographyLink']
    ATypographyParagraph: typeof import('ant-design-vue/es')['TypographyParagraph']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    ChatMessage: typeof import('./../components/AtomicComponents/ChatMessage.vue')['default']
    ChatMessageList: typeof import('./../components/ChatMessageList.vue')['default']
    CreditCardOutlined: typeof import('@ant-design/icons-vue')['CreditCardOutlined']
    GiftCapsule: typeof import('./../components/AtomicComponents/GiftCapsule.vue')['default']
    GiftCapsulePanel: typeof import('./../components/GiftCapsulePanel.vue')['default']
    GiftCard: typeof import('./../components/AtomicComponents/GiftCard.vue')['default']
    GiftCardPanel: typeof import('./../components/GiftCardPanel.vue')['default']
    GiftOutlined: typeof import('@ant-design/icons-vue')['GiftOutlined']
    HBadge: typeof import('./../components/AtomicComponents/HBadge.vue')['default']
    HFont: typeof import('./../components/AtomicComponents/HFont.vue')['default']
    LockOutlined: typeof import('@ant-design/icons-vue')['LockOutlined']
    MessageOutlined: typeof import('@ant-design/icons-vue')['MessageOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingOutlined: typeof import('@ant-design/icons-vue')['SettingOutlined']
    SmileOutlined: typeof import('@ant-design/icons-vue')['SmileOutlined']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
  }
}
